version: '2'
services:
    fepbapi-app:
        image: fepb-api/fepbapi
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://35.225.195.101:5432/fepbapi
            - SPRING_DATASOURCE_USERNAME=victorximenis
            - SPRING_DATASOURCE_PASSWORD=pf13.500
            - JHIPSTER_SLEEP=10
        ports:
            - 8080:8080
    fepbapi-postgresql:
        image: postgres:10.4
        environment:
            - POSTGRES_USER=fepbapi
            - POSTGRES_PASSWORD=
    
