version: '2'
services:
    fepbapi-app:
        image: fepbapi
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://fepbapi-postgresql:5432/fepbapi
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fepbapi-postgresql:
        extends:
            file: postgresql.yml
            service: fepbapi-postgresql
