version: '2'
services:
    fepbapi-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/fepbapi/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=fepbapi
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
